version: '3'
services:
  web:
    build: ./application
    ports:
      - "3000:3000"
    command: bash -c "cd my_rails_app && bundle install --path=/cache && bin/setup && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./application:/my_app:delegated
      - ./application/gem_cache:/cache:cached
    depends_on:
      - db
  db:
    image: postgres
