version: '3'
services:
  web:
    build: ./application
    ports:
      - "3000:3000"
    command: bash -c "cd my_rails_app && bundle install --path=/cache && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./application:/my_app
      - ./application/gem_cache:/cache
